http:
  routers:
    wled:
      entryPoints:
        - "https"
      rule: "Host(`wled.$DOMAIN_NAME`)"
      middlewares:
        - chain-oauth
      tls:
        - tls-ops
      service: wled

services:
    wled:
      loadBalancer:
        servers:
          - url: "http://192.168.1.22:80"
        passHostHeader: true
