http:
  routers:
    wled-rtr:
      entryPoints:
        - websecure
      rule: 'Host(`wled.{{ env "DOMAIN_NAME" }}`)'
      middlewares:
        - chain-oauth
      tls:
        options: tls-opts@file
      service: wled-svc

    hdhomerun-rtr:
      entryPoints:
        - websecure
      rule: 'Host(`hdhomerun.{{ env "DOMAIN_NAME" }}`)'
      middlewares:
        - chain-oauth
      tls:
        options: tls-opts@file
      service: hdhomerun-svc

  services:
    wled-svc:
      loadBalancer:
        servers:
          - url: {{ env "WLED_IP" }}
        passHostHeader: true

    hdhomerun-svc:
      loadBalancer:
        servers:
          - url: {{ env "HDHOMERUN_IP" }}
        passHostHeader: true
