http:
  routers:
    wled:
      entryPoints:
        - "https"
      rule: 'Host(`wled.{{ env "DOMAIN_NAME" }}`)'
      middlewares:
        - chain-oauth
      tls:
        - tls-opts
      service: wled

    hdhomerun:
      entryPoints:
        - "https"
      rule: 'Host(`hdhomerun.{{ env "DOMAIN_NAME" }}`)'
      middlewares:
        - chain-oauth
      tls:
        - tls-opts
      service: hdhomerun

  services:
    wled:
      loadBalancer:
        servers:
          - url: {{ env "WLED_IP" }}
        passHostHeader: true

    hdhomerun:
      loadBalancer:
        servers:
          - url: {{ env "HDHOMERUN_IP" }}
        passHostHeader: true
