http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          - middlewares-traefik-bouncer
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-compress
    
    chain-oauth:
      chain:
        middlewares:
          - middlewares-traefik-bouncer
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-oauth
          - middlewares-compress
