networks:
  bar-net:
    name: bar-net
    driver: bridge

services:
  bar-search:
    image: getmeili/meilisearch:v1.8
    container_name: bar-search
    networks:
      - bar-net
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    volumes:
      - $DOCKER_DIR/app-data/bar-assistant/meilisearch:/meili_data
    environment:
      MEILI_MASTER_KEY: $MEILI_MASTER_KEY
      MEILI_ENV: production

  bar-api:
    image: barassistant/server:v4
    container_name: bar-api
    depends_on:
      - bar-search
    networks:
      - bar-net
      - traefik_proxy
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    volumes:
      - $DOCKER_DIR/app-data/bar-assistant/bar:/var/www/cocktails/storage/bar-assistant
    environment:
      APP_URL: http://bar-api:8080
      MEILISEARCH_KEY: $MEILI_MASTER_KEY
      MEILISEARCH_HOST: http://bar-search:7700
      # REDIS_HOST: redis # Remove if not using redis
      CACHE_DRIVER: file # Change to "file" if not using redis
      SESSION_DRIVER: file # Change to "file" if not using redis
      ALLOW_REGISTRATION: true

  bar-web:
    image: barassistant/salt-rim:v3
    container_name: bar-web
    depends_on:
      - bar-api
    networks:
      - bar-net
      - traefik_proxy
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    environment:
      API_URL: http://bar-api:8080
      MEILISEARCH_URL: http://bar-search:7700/search
    labels:
      - "traefik.enable=true"
      # HTTP Routers Auth
      - "traefik.http.routers.bar-rtr.entrypoints=websecure"
      - "traefik.http.routers.bar-rtr.rule=Host(`bar.$DOMAIN_NAME`)"
      # Middlewares
      - "traefik.http.routers.bar-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.bar-rtr.service=bar-svc"
      - "traefik.http.services.bar-svc.loadbalancer.server.port=8080"
      # Backup
      - "backup.stop"
