services:
  changedetection:
    image: dgtlmoon/changedetection.io:latest
    container_name: changedetection
    networks:
      - traefik_proxy
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BASE_URL: https://change.$DOMAIN_NAME
      PLAYWRIGHT_DRIVER_URL: ws://changedetection-chrome:3000/
    volumes:
      - $DOCKER_DIR/app-data/changedetection:/datastore
    depends_on:
      - changedetection-chrome
    labels:
      - "traefik.enable=true"
      # HTTP Routers Auth
      - "traefik.http.routers.change-rtr.entrypoints=websecure"
      - "traefik.http.routers.change-rtr.rule=Host(`change.$DOMAIN_NAME`)"
      # Middlewares
      - "traefik.http.routers.change-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.change-rtr.service=change-svc"
      - "traefik.http.services.change-svc.loadbalancer.server.port=5000"

  changedetection-chrome:
    container_name: changedetection-chrome
    image: browserless/chrome
    restart: unless-stopped
    networks:
      - traefik_proxy
    security_opt:
      - no-new-privileges=true
