services:
  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      UMASK_SET: 022
    volumes:
      - $DOCKER_DIR/app-data/deluge:/config
      - $DOWNLOAD_DIR:/downloads
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.deluge-rtr.entrypoints=websecure"
      - "traefik.http.routers.deluge-rtr.rule=Host(`deluge.$DOMAIN_NAME`)"
      # Middlewares
      - "traefik.http.routers.deluge-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.deluge-rtr.service=deluge-svc"
      - "traefik.http.services.deluge-svc.loadbalancer.server.port=8112"
