services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    networks:
      - t2_proxy
      - socket_proxy
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: status=running
      DOCKER_HOST: $SOCKET_PROXY
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.dozzle-rtr.entrypoints=https"
      - "traefik.http.routers.dozzle-rtr.rule=Host(`dozzle.$DOMAIN_NAME`)"
      # Middlewares
      - "traefik.http.routers.dozzle-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.dozzle-rtr.service=dozzle-svc"
      - "traefik.http.services.dozzle-svc.loadbalancer.server.port=8080"
