services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    privileged: true
    networks:
      - traefik_proxy
      - socket_proxy
    pid: host
    environment:
      TZ: $TZ
      GLANCES_OPT: -w --fs-free-space
      DOCKER_HOST: $SOCKET_PROXY
    volumes:
      - $MEDIA_DIR:/data/hdd1:ro
      - $DOCKER_DIR/app-data/glances/glances.conf:/etc/glances.conf
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.glances-rtr.entrypoints=websecure"
      - "traefik.http.routers.glances-rtr.rule=Host(`glances.$DOMAIN_NAME`)"
      # Middlewares
      - "traefik.http.routers.glances-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.glances-rtr.service=glances-svc"
      - "traefik.http.services.glances-svc.loadbalancer.server.port=61208"
