services:
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    volumes:
      - $DOCKER_DIR/app-data/lidarr:/config
      - $DOWNLOAD_DIR:/downloads
      - $MEDIA_DIR/music:/music
      - "/etc/localtime:/etc/localtime:ro"
      # Keep backups smaller/simpler. This data can be regenerated/redownloaded by Lidarr.
      - $DOCKER_DIR/temp/lidarr/MediaCover:/config/MediaCover
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers Auth Bypass
      - "traefik.http.routers.lidarr-rtr-bypass.entrypoints=websecure"
      - "traefik.http.routers.lidarr-rtr-bypass.rule=Host(`lidarr.$DOMAIN_NAME`) && (Headers(`X-Api-Key`, `$LIDARR_API_KEY`) || Query(`apikey`, `$LIDARR_API_KEY`))"
      - "traefik.http.routers.lidarr-rtr-bypass.priority=100"
      # HTTP Routers Auth
      - "traefik.http.routers.lidarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.lidarr-rtr.rule=Host(`lidarr.$DOMAIN_NAME`)"
      - "traefik.http.routers.lidarr-rtr.priority=99"
      # Middlewares
      - "traefik.http.routers.lidarr-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.lidarr-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.lidarr-rtr.service=lidarr-svc"
      - "traefik.http.routers.lidarr-rtr-bypass.service=lidarr-svc"
      - "traefik.http.services.lidarr-svc.loadbalancer.server.port=8686"
      # Backup
      - "backup.stop"
