services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    volumes:
      - $DOCKER_DIR/app-data/overseerr:/app/config
      # Keep backups smaller/simpler. This data can be regenerated/redownloaded by Overseerr.
      - $DOCKER_DIR/temp/overseerr/cache:/app/config/cache
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.overseerr-rtr.entrypoints=https"
      - "traefik.http.routers.overseerr-rtr.rule=Host(`request.$DOMAIN_NAME`)"
      # Middlewares
      - "traefik.http.routers.overseerr-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.overseerr-rtr.service=overseerr-svc"
      - "traefik.http.services.overseerr-svc.loadbalancer.server.port=5055"
      # Backup
      - "backup.stop"
