services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - traefik_proxy
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    volumes:
      - $DOCKER_DIR/app-data/prowlarr:/config
      # Keep backups smaller/simpler. This data can be regenerated/redownloaded by Prowlarr.
      - $DOCKER_DIR/temp/prowlarr/Definitions:/config/Definitions
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.prowlarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr-rtr.rule=Host(`prowlarr.$DOMAIN_NAME`)"
      # Middlewares
      - "traefik.http.routers.prowlarr-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.prowlarr-rtr.service=prowlarr-svc"
      - "traefik.http.services.prowlarr-svc.loadbalancer.server.port=9696"
      # Backup
      - "backup.stop"
