services:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    networks:
      - traefik_proxy
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    volumes:
      - $DOCKER_DIR/app-data/seerr:/app/config
      # Keep backups smaller/simpler. This data can be regenerated/redownloaded by Overseerr.
      - $DOCKER_DIR/temp/seerr/cache:/app/config/cache
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.seerr-rtr.entrypoints=websecure"
      - "traefik.http.routers.seerr-rtr.rule=Host(`request.$DOMAIN_NAME`)"
      # Middlewares
      - "traefik.http.routers.seerr-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.seerr-rtr.service=seerr-svc"
      - "traefik.http.services.seerr-svc.loadbalancer.server.port=5055"
      # Backup
      - "backup.stop"
