services:
  speedtest:
    container_name: speedtest
    image: linuxserver/speedtest-tracker:latest
    networks:
      - traefik_proxy
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    volumes:
      - $DOCKER_DIR/app-data/speedtest:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.speedtest-rtr.entrypoints=websecure"
      - "traefik.http.routers.speedtest-rtr.rule=Host(`speedtest.$DOMAIN_NAME`)"
      # Middlewares
      - "traefik.http.routers.speedtest-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.speedtest-rtr.service=speedtest-svc"
      - "traefik.http.services.speedtest-svc.loadbalancer.server.port=80"
      # Backup
      - "backup.stop"
