services:
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    volumes:
      - $DOCKER_DIR/app-data/tautulli/config:/config
      - $DOCKER_DIR/app-data/plexms/Library/Application Support/Plex Media Server/Logs:/logs:ro  # For tautulli Plex log viewer
      # Keep backups smaller/simpler. This data can be regenerated/redownloaded by Tautulli.
      - $DOCKER_DIR/temp/tautulli/cache:/config/cache
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers Auth Bypass
      - "traefik.http.routers.tautulli-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.tautulli-rtr-bypass.rule=Host(`tautulli.$DOMAIN_NAME`) && Query(`apikey`, `$TAUTULLI_DEVICE_TOKEN`)"
      - "traefik.http.routers.tautulli-rtr-bypass.priority=100"
      # HTTP Routers
      - "traefik.http.routers.tautulli-rtr.entrypoints=https"
      - "traefik.http.routers.tautulli-rtr.rule=Host(`tautulli.$DOMAIN_NAME`)"
      - "traefik.http.routers.tautulli-rtr.priority=99"
      # Middlewares
      - "traefik.http.routers.tautulli-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.tautulli-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.tautulli-rtr.service=tautulli-svc"
      - "traefik.http.routers.tautulli-rtr-bypass.service=tautulli-svc"
      - "traefik.http.services.tautulli-svc.loadbalancer.server.port=8181"
      # Backup
      - "backup.stop"
